// <auto-generated />
using System;
using Metasite.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Metasite.DAL.Migrations
{
    [DbContext(typeof(MSContext))]
    partial class MSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Metasite.DAL.Entities.EventLog", b =>
                {
                    b.Property<int>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Duration");

                    b.Property<int>("EventTypeId");

                    b.Property<int>("MsIsdnId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("EventLogId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("MsIsdnId");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("Metasite.DAL.Entities.EventType", b =>
                {
                    b.Property<int>("EventTypeId");

                    b.Property<string>("Type");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventType");
                });

            modelBuilder.Entity("Metasite.DAL.Entities.MsIsdn", b =>
                {
                    b.Property<int>("MsIsdnId");

                    b.Property<string>("MsIsdnNumber")
                        .HasMaxLength(11);

                    b.HasKey("MsIsdnId");

                    b.ToTable("MsIsdn");
                });

            modelBuilder.Entity("Metasite.DAL.Entities.EventLog", b =>
                {
                    b.HasOne("Metasite.DAL.Entities.EventType", "EventType")
                        .WithMany("EventLogs")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Metasite.DAL.Entities.MsIsdn", "MsIsdn")
                        .WithMany("EventLogs")
                        .HasForeignKey("MsIsdnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
